### ISSUE TITLE
INPUT__INTERNAL-STRICT-MODE not set for @actions/core

### ISSUE THREAD

**Issue by gigamonster256** [DeterminateSystems/update-flake-lock#106]
My github action following DeterminateSystems/update-flake-lock@main failed this morning with the following error:
```bash
TypeError: Input does not meet YAML 1.2 "Core Schema" specification: _internal-strict-mode
Support boolean input list: `true | True | TRUE | false | False | FALSE`
```

This seems to come from INPUT__INTERNAL-STRICT-MODE not being set so @actions/core cannot read the value and passes an empty string to the parser which gives the above error.

**Comment by lucperkins** [comment]
@gigamonster256 This should be fixed now. If not, please let us know!

**Comment by lucperkins** [comment]
Actually, #107 was not the right solution. #108 should be.
