### ISSUE TITLE
Update specific inputs

### ISSUE THREAD

**Issue by a-kenji** [DeterminateSystems/update-flake-lock#14]
Thank you for this project!
Is it possible to have this action update specific inputs?

**Comment by cole-h** [comment]
Thanks for the report! https://github.com/DeterminateSystems/update-flake-lock/pull/15 should support this -- I'll cut a new release later.

**Comment by a-kenji** [comment]
Thank you!

**Comment by cole-h** [comment]
I just released https://github.com/DeterminateSystems/update-flake-lock/releases/tag/v5 -- thanks again!

**Comment by a-kenji** [comment]
Thank you, it works great!

But it seems that I need to add the script now to the root of my project.
Is that expected?

```
/home/runner/work/_temp/dd767b88-96e4-4375-8ba5-bd14e9de88d3.sh: line 1: ./update-input-or-inputs.sh: No such file or directory
```

If I add the script, then the action proceeds without problems.

**Comment by cole-h** [comment]
Not expected indeed. I'll see if I can't figure something out.

**Comment by cole-h** [comment]
I've opened https://github.com/DeterminateSystems/update-flake-lock/issues/18 -- unfortunately, I won't be able to take a look until tomorrow. In the meantime, if you use `DeterminateSystems/update-flake-lock@0d0deff8bd5e1859adc80318e918e5e90bd71d80`, that should give you what you want (which is the commit before I broke the script out into its own file).

**Comment by a-kenji** [comment]
Awesome, thank you.
And no need to rush!
