### ISSUE TITLE
Per-input update requires the script in-repo

### ISSUE THREAD

**Issue by cole-h** [DeterminateSystems/update-flake-lock#18]
Thank you, it works great!

But it seems that I need to add the script now to the root of my project.
Is that expected?

```
/home/runner/work/_temp/dd767b88-96e4-4375-8ba5-bd14e9de88d3.sh: line 1: ./update-input-or-inputs.sh: No such file or directory
```

If I add the script, then the action proceeds without problems.

_Originally posted by @a-kenji in https://github.com/DeterminateSystems/update-flake-lock/issues/14#issuecomment-985076960_

I don't know if there's an easy way to resolve this. Maybe it's not actually possible to break the logic out into a script.

**Comment by cole-h** [comment]
@a-kenji -- thanks for the report! I've just released v6 to fix this issue. Sorry for any inconvenience! https://github.com/DeterminateSystems/update-flake-lock/releases/tag/v6

**Comment by a-kenji** [comment]
Thank you!
