### ISSUE TITLE
Updating lock files at non-standard locations (devenv.lock)

### ISSUE THREAD

**Issue by domenkozar** [DeterminateSystems/update-flake-lock#59]
This would be really nice to have, so I can recommend it for devenv.sh projects.

**Comment by cole-h** [comment]
If you can show / link to an example of how a user might do this manually (update a lockfile in a non-standard location with `nix`), I think it might not be too difficult to implement.

**Comment by domenkozar** [comment]
Once you [install](https://devenv.sh/getting-started/#installation) devenv, you run `devenv update`.
