### ISSUE TITLE
Consider nix installer being explicit

### ISSUE THREAD

**Issue by domenkozar** [DeterminateSystems/update-flake-lock#6]
Installer action comes with nix.conf options, different installers, etc.

One way would be to expose those via this action, but then what's the point of doing that? :)

**Comment by domenkozar** [comment]
`install_nix` sounds good :)

> because it needs some new feature or bugfix and now there's 2 different versions in use).

That makes sense, but it's surprising/out of control for those that don't maintain this action :)

I'd expect the install action to always default to the latest Nix (starting with Nix 2.4 rc1).

As soon as that changes to a bugfix release you might need internally, that's unexpected for me as a downstream user.

Thanks for explaining the motivation!

**Comment by cole-h** [comment]
Definitely fair.

Is `2.4pre-rc1` the same as what you're referring to as "Nix 2.4 rc1"? (It's the `pre` that's throwing me off -- is it "pre-rc1" or "2.4pre" because it's not a true 2.4 release yet.)
