### ISSUE TITLE
Separate PRs for inputs

### ISSUE THREAD

**Issue by lovesegfault** [DeterminateSystems/update-flake-lock#69]
Is there a way to create separate PRs for each input being updated, instead of a PR including the updates of multiple inputs?

It could query `locks.nodes.root.inputs` in `nix flake metadata --json`, and then just individually update/create a PR for each one, perhaps?

**Comment by cole-h** [comment]
You could use the inputs targeting that already exists (https://github.com/DeterminateSystems/update-flake-lock#example-updating-specific-inputs) and use multiple jobs each targeting a different input, I'd bet.

**Comment by cole-h** [comment]
Looks like that's what you did in https://github.com/DeterminateSystems/update-flake-lock/issues/70, so I'm going to close this. Feel free to reopen if you have anything else to add!
