### ISSUE TITLE
Custom options to `nix flake` command

### ISSUE THREAD

**Issue by xgroleau** [DeterminateSystems/update-flake-lock#72]
Adding the possibility to use custom options to ` nix flake` command could be useful.
For example, some of our flakes uses a private repositories so usually the access token is passed.

`nix --access-tokens github.com=${{ secrets.GH_TOKEN }} ....`

The current options does not seem to provide a way to pass custom options or flags.

**Comment by cole-h** [comment]
That should probably be set in your nix.conf file. See https://github.com/DeterminateSystems/nix-installer-action/#configuration or https://github.com/cachix/install-nix-action#inputs-specify-using-with, depending on which action you use to install Nix in GitHub Actions.

**Comment by xgroleau** [comment]
We are using a self hosted GitHub Runner on a NixOS machine, so we do not use an action to install nix since it's already available/installed. Writing the nix.conf file manually or as an action is still an option (this is what we do in  the meantime), but I would prefer avoid modifying the `$HOME` directory  if possible.
