### ISSUE TITLE
`DamianReeves/write-file-action` depends on `node16`

### ISSUE THREAD

**Issue by aanderse** [DeterminateSystems/update-flake-lock#93]
what happens when you try to run `update-flake-lock` on a `self-hosted` [github-runner](https://search.nixos.org/options?channel=23.11&from=0&size=50&sort=relevance&type=packages&query=services.github-runners.) on NixOS?

```
Run DamianReeves/write-file-action@v1.2
Error: An error occurred trying to start process '/nix/store/d9hc30rhc1vqh5l659rz51ch5ki490bn-github-runner-2.311.0/lib/externals/node16/bin/node' with working directory '/run/github-runner/runner3/ds-research/ds-research'. No such file or directory
```

action items:
- make PR against `DamianReeves/write-file-action` to update `node` version
- update this action to include newer version of `write-file-action`

i'll see what i can find time to do, but thought it best to log an item here in case someone else gets around to fixing this before i do

thanks team :bowing_man:

**Comment by cole-h** [comment]
Sorry for the delay -- fixed in https://github.com/DeterminateSystems/update-flake-lock/pull/96!

I'll try to get a release out tomorrow with most (or hopefully all) of the node20 bumps. (The only blocker for all-node20 is https://github.com/pedrolamas/handlebars-action/pull/786 I believe.)

**Comment by aanderse** [comment]
thanks @cole-h!

**Comment by cole-h** [comment]
https://github.com/DeterminateSystems/update-flake-lock/releases/tag/v21 has been released!
