### ISSUE TITLE
Action fails with "cannot read properties of undefined"

### ISSUE THREAD

**Issue by devusb** [DeterminateSystems/update-flake-lock#94]
Starting yesterday, the action fails to complete with the following message:
```
Create or update the pull request
  Attempting creation of pull request
  A pull request already exists for devusb:update_flake_lock_action
  Fetching existing pull request
  Attempting update of pull request
  Error: Cannot read properties of undefined (reading 'number')
```
Believe [this is related](https://github.com/peter-evans/create-pull-request/issues/2790) -- looks like there may have been a breaking change to GitHub's PR API -- `create-pull-request` updated `v6` to address it.

**Comment by devusb** [comment]
Closed by #95.

**Comment by cole-h** [comment]
Thanks for fixing this! I'll try to get a new version out some time tomorrow (I'm also hoping to squash all or almost all of the node16->node20 dependency updates in the same version).

**Comment by cole-h** [comment]
https://github.com/DeterminateSystems/update-flake-lock/releases/tag/v21 has been released!
